name: thin_divider
description: Divider not show in browser, thin_divider is compatible web browser
version: 1.0.4
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/ thin_divider

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  #  entangle:
  #    path: /Users/pillar/work/darts/dart_entangle
  flutter:
    sdk: flutter
